### ISSUE TITLE
[Suggestion] Fixed position for buttons

### ISSUE THREAD

**Issue by silverwings15** [sajadhsm/new-word-tab#18]
Hey, right now the buttons are placed horizontally to the word, with the placement being determined by the word length. Would it be a better idea if you move the buttons below the word? that way they can stay fixed and it'll be easier to clear multiple words in a row.

**Comment by sajadhsm** [comment]
Hey. Nice suggestion. The word phonetic text and audio button cause the other buttons to move around.

There are 2 simple solutions for now:

1. Reversing the order of the buttons so the phonetic section moves to the left which results in other buttons always being in the same position. The problem with this solution is that the jumping happens when the screen size is small and the buttons are automatically moved below the word.

![image](https://user-images.githubusercontent.com/20022818/154918846-1fa581e7-add6-49aa-8336-56c9609e94c5.png)

2. As you suggested, move the actions below the word. This keeps the current order but it makes the right side of the word blank which I think doesn't have a nice UI.

![image](https://user-images.githubusercontent.com/20022818/154919651-58c13565-b1cb-4c44-804c-6a772d9be8ec.png)

I think adding a new option in the settings page to set the actions buttons' position would be a good thing. So each user can set the position based on their preference.

* Inline (Horizontal)
* Inline reversed (Horizontal reversed)
* Below the word (Vertical)

We need to decide which position be the default option.

**Comment by silverwings15** [comment]
would be awesome if you can implement all three, the more options the better. you're right about about there being too much empty space in my method. i think the current default is the safest bet visually so might as well stick with that. heavy users will learn to configure the setting on their own anyway.

**Comment by sajadhsm** [comment]
I agree. I'll try to implement them this week :D

BTW what should we call those options?

1. Inline / Inline reversed / Below the word
2. Horizontal / Horizontal reversed / Vertical

Do you have any better or more descriptive names in mind?

**Comment by silverwings15** [comment]
i might be mistaken but can inline not refer to either a horizontal or vertical arrangement? in which case i would go with 2. you can maybe also go with something like Dense/Sparse/Sparse reversed

**Comment by sajadhsm** [comment]
Hmmm, I thought like CSS inline and block display properties which result in a similar look that we want. I don't know, maybe they can refer to both horizontal and vertical arrangements out of CSS context.

Your suggestion is good too. I'll go with one of them eventually. Thanks 👍
